
CREATE USER mini_dish_db_manager WITH PASSWORD '123456789';

CREATE DATABASE mini_dish_db OWNER mini_dish_db_manager;

\c mini_dish_db


CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION mini_dish_db_manager;

GRANT USAGE, CREATE ON SCHEMA public TO mini_dish_db_manager;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mini_dish_db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO mini_dish_db_manager;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mini_dish_db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO mini_dish_db_manager;

GRANT USAGE, CREATE ON SCHEMA public TO mini_dish_db_manager;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mini_dish_db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO mini_dish_db_manager;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mini_dish_db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO mini_dish_db_manager;
